#!/usr/bin/with-contenv sh

umask 022

union_mount_command="unionfs-fuse -o uid=${PUID:-911} -o gid=${PGID:-911} $UNION_MOUNT_OPTIONS /local=RW:/rcache=RO /union"

echo "Executing => $union_mount_command"
exec \
	s6-setuidgid abc $union_mount_command
