#!/usr/bin/with-contenv sh

umask 022

if [ -z "$RCLONE_REMOTE_MOUNT" ]; then
  echo "Error: RCLONE_REMOTE_MOUNT environment variable was not passed to the container."
  exit 1
fi

rclone_mount_command="rclone mount --config=/config/.rclone.conf --allow-other $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT /rclone"

echo "Executing => $rclone_mount_command"
exec \
	s6-setuidgid abc $rclone_mount_command
