#!/usr/bin/with-contenv sh

umask 022

if [ -z "$RCLONE_REMOTE_MOUNT" ]; then
  echo "Error: RCLONE_REMOTE_MOUNT environment variable was not passed to the container."
  exit 1
fi

if [ -z "$RCLONE_LOCAL_MOUNT" ]; then
  echo "Error: RCLONE_LOCAL_MOUNT environment variable was not passed to the container."
  exit 1
fi

if [ -z "$RCLONE_UNION_MOUNT" ]; then
  echo "Error: RCLONE_UNION_MOUNT environment variable was not passed to the container."
  exit 1
fi

remote_mount_command="rclone mount --config=/config/.rclone.conf --allow-other $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT /data"

echo "Executing => $remote_mount_command"
exec \
	s6-setuidgid abc $remote_mount_command
	
union_mount_command="rclone mount --config=/config/.rclone.conf --allow-other $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT /data"

echo "Executing => $union_mount_command"
exec \
	s6-setuidgid abc $union_mount_command
	
### MORE EDITS HERE...
